# coding: utf-8

"""
    FeersumNLU API

    This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.

    OpenAPI spec version: 2.0.3
    Contact: nlu@feersum.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class NewWord(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, new_word=None, similar_to=None):
        """
        NewWord - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'new_word': 'str',
            'similar_to': 'str'
        }

        self.attribute_map = {
            'new_word': 'new_word',
            'similar_to': 'similar_to'
        }

        self._new_word = new_word
        self._similar_to = similar_to


    @property
    def new_word(self):
        """
        Gets the new_word of this NewWord.


        :return: The new_word of this NewWord.
        :rtype: str
        """
        return self._new_word

    @new_word.setter
    def new_word(self, new_word):
        """
        Sets the new_word of this NewWord.


        :param new_word: The new_word of this NewWord.
        :type: str
        """
        if new_word is None:
            raise ValueError("Invalid value for `new_word`, must not be `None`")

        self._new_word = new_word

    @property
    def similar_to(self):
        """
        Gets the similar_to of this NewWord.


        :return: The similar_to of this NewWord.
        :rtype: str
        """
        return self._similar_to

    @similar_to.setter
    def similar_to(self, similar_to):
        """
        Sets the similar_to of this NewWord.


        :param similar_to: The similar_to of this NewWord.
        :type: str
        """
        if similar_to is None:
            raise ValueError("Invalid value for `similar_to`, must not be `None`")

        self._similar_to = similar_to

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
