from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from feersum_nlu.api.api_keys_api import ApiKeysApi
from feersum_nlu.api.crf_entity_extractors_api import CrfEntityExtractorsApi
from feersum_nlu.api.dashboard_api import DashboardApi
from feersum_nlu.api.data_objects_api import DataObjectsApi
from feersum_nlu.api.date_parsers_api import DateParsersApi
from feersum_nlu.api.duckling_entity_extractors_api import DucklingEntityExtractorsApi
from feersum_nlu.api.faq_matchers_api import FaqMatchersApi
from feersum_nlu.api.health_api import HealthApi
from feersum_nlu.api.image_classifiers_api import ImageClassifiersApi
from feersum_nlu.api.image_datasets_api import ImageDatasetsApi
from feersum_nlu.api.image_readers_api import ImageReadersApi
from feersum_nlu.api.intent_classifiers_api import IntentClassifiersApi
from feersum_nlu.api.language_recognisers_api import LanguageRecognisersApi
from feersum_nlu.api.lr4_language_recognisers_api import Lr4LanguageRecognisersApi
from feersum_nlu.api.params_api import ParamsApi
from feersum_nlu.api.regex_entity_extractors_api import RegexEntityExtractorsApi
from feersum_nlu.api.sentence_translators_api import SentenceTranslatorsApi
from feersum_nlu.api.sentiment_detectors_api import SentimentDetectorsApi
from feersum_nlu.api.synonym_entity_extractors_api import SynonymEntityExtractorsApi
from feersum_nlu.api.text_classifiers_api import TextClassifiersApi
from feersum_nlu.api.text_datasets_api import TextDatasetsApi
