from __future__ import absolute_import

# import apis into api package
from .dashboard_api import DashboardApi
from .date_parsers_api import DateParsersApi
from .duckling_entity_extractors_api import DucklingEntityExtractorsApi
from .faq_matchers_api import FaqMatchersApi
from .intent_classifiers_api import IntentClassifiersApi
from .lr4_language_recognisers_api import Lr4LanguageRecognisersApi
from .regex_entity_extractors_api import RegexEntityExtractorsApi
from .sentiment_detectors_api import SentimentDetectorsApi
from .similarity_entity_extractors_api import SimilarityEntityExtractorsApi
from .text_classifiers_api import TextClassifiersApi
from .word_manifolds_api import WordManifoldsApi
